[package]
name = "oxidoist-api"
version = "0.1.0"
authors = ["Christopher Leggett <chris@leggett.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
